### ISSUE TITLE
Ask about emacs mode

### ISSUE THREAD

**Issue by Ailrun** [snu-sf-class/pl2016#1]
I saw that professor use emacs with coq-mode.
I use emacs too, but I can't find the actual mode for coq 8.4pl6.

I found these two sources
PG(including coq mode) https://github.com/ProofGeneral/PG
Company-coq(autocomplete for coq) https://github.com/cpitclaudel/company-coq#setup

Is these things right answer for emacs settings for coq 8.4pl6?
If not, could you share the piece of your emacs setting for coq, please?

**Comment by jeehoonkang** [comment]
I recommend you to use Company-Coq.  For me, the link you posted (https://github.com/cpitclaudel/company-coq#setup) just worked fine.
