### ISSUE TITLE
window에서 coq을 어떻게 사용하는지 문의드립니다.!

### ISSUE THREAD

**Issue by ckdrl2723** [snu-sf-class/pl2016#13]
제가 왕초보라서.. 거의 잘 알지 못합니다 ㅠㅠ

coq을 깔고 coqide를 사용해서 숙제를 해보려고 했는데 처음 숙제파일을 받는 것 부터 막힙니다.

파일을 받는 것은 어떻게 해야 하나요? 또 어느 경로에 지정해야 하나요? 

따로 받는 방식이 없으면  일일이 코드 복사해서 복붙하고 저장하는 식으로 해보려고 합니다..

**Comment by taehwoi** [comment]
https://desktop.github.com/

이 프로그램을 사용하시면 굳이 커맨드라인을 거치지 않고 편하게 깃을 사용하실 수 있을 것 같습니다.

이 프로그램으로 이 저장소를 적절한 위치에 클론하신 다음 사용하면 될 것 같아요.

**Comment by ckdrl2723** [comment]
감사합니다!

**Comment by jeehoonkang** [comment]
숙제 파일은 https://github.com/snu-sf-class/pl2016 에서 "Download Zip"으로 받으실 수도 있습니다.

**Comment by jeehoonkang** [comment]
@ckdrl2723  문제가 여전히 남아있는지 여쭤보고 싶습니다.

**Comment by ckdrl2723** [comment]
답변 감사드립니다! close 하겠습니다!

**Comment by jeehoonkang** [comment]
- 보다 구체적인 매뉴얼을 작성하였습니다: https://github.com/snu-sf-class/pl2016/issues/16
- 추후 Windows 관련 질문은 https://github.com/snu-sf-class/pl2016/issues/16 로 병합하겠습니다.
