### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by leegangtoe** [snu-sf-class/pl2016#14]
If i type "make" in 00 directory to compile codes, the error occurs.

This is error by make
(echo "-R . assignment"; \ echo D.v P01.v P02.v P03.v E01.v E02.v E03.v) > _CoqProject coq_makefile -f _CoqProject -o Makefile.coq

then, next two error lines occur.
make: coq_makefile: No such file or directory
make:**\* [Makefile.coq] Error 1

I do not understand why errors occur.If i type "make" in 00 directory to compile codes, the error occurs.

This is error by make
(echo "-R . assignment"; \ echo D.v P01.v P02.v P03.v E01.v E02.v E03.v) > _CoqProject coq_makefile -f _CoqProject -o Makefile.coq

then, next two error lines occur.
make: coq_makefile: No such file or directory
make:**\* [Makefile.coq] Error 1

I have same error and i typed which coq_makefile, it says no coq_makefile. then what should i do?

**Comment by jeehoonkang** [comment]
Duplicate #10

**Comment by leegangtoe** [comment]
i typed which coq_makefile, it says no coq_makefile in my path. what do i have to do?
