### ISSUE TITLE
problem with making

### ISSUE THREAD

**Issue by leegangtoe** [snu-sf-class/pl2016#15]
cygwin을 다운받은후 gcc를 설치하고 make 명령어를 쓰니

$ make
(echo "-R . assignment"; \
         echo D.v P01.v P02.v P03.v E01.v E02.v E03.v) > _CoqProject
coq_makefile -f _CoqProject -o Makefile.coq
make: coq_makefile: 명령을 찾지 못했음
Makefile:22: 'Makefile.coq' 타겟에 대한 명령이 실패했습니다
make: **\* [Makefile.coq] 오류 127

와 같은 error message가 떴습니다.
그래서 cygwin의 bin폴더에 coq_makefile을 넣고 make 명령어를 실행했습니다.
그랬더니

$ make
(echo "-R . assignment"; \
         echo D.v P01.v P02.v P03.v E01.v E02.v E03.v) > _CoqProject
coq_makefile -f _CoqProject -o Makefile.coq
make -f Makefile.coq P01.vo P02.vo P03.vo
make[1]: 디렉터리 '/home/leegangtoe/pl2016/assignments/00' 들어감
/bin/sh: coqtop: command not found
"coqdep" -c -slash -R . assignment "D.v" > "D.v.d" || ( RV=$?; rm -f "D.v.d"; exit ${RV} )
/bin/sh: coqdep: command not found
"coqdep" -c -slash -R . assignment "P01.v" > "P01.v.d" || ( RV=$?; rm -f "P01.v.d"; exit ${RV} )
/bin/sh: coqdep: command not found
"coqdep" -c -slash -R . assignment "P02.v" > "P02.v.d" || ( RV=$?; rm -f "P02.v.d"; exit ${RV} )
/bin/sh: coqdep: command not found
"coqdep" -c -slash -R . assignment "P03.v" > "P03.v.d" || ( RV=$?; rm -f "P03.v.d"; exit ${RV} )
/bin/sh: coqdep: command not found
"coqdep" -c -slash -R . assignment "E01.v" > "E01.v.d" || ( RV=$?; rm -f "E01.v.d"; exit ${RV} )
/bin/sh: coqdep: command not found
"coqdep" -c -slash -R . assignment "E02.v" > "E02.v.d" || ( RV=$?; rm -f "E02.v.d"; exit ${RV} )
/bin/sh: coqdep: command not found
"coqdep" -c -slash -R . assignment "E03.v" > "E03.v.d" || ( RV=$?; rm -f "E03.v.d"; exit ${RV} )
/bin/sh: coqdep: command not found
"coqc"  -q  -R . assignment   P01
/bin/sh: coqc: command not found
Makefile.coq:204: 'P01.vo' 타겟에 대한 명령이 실패했습니다
make[1]: **\* [P01.vo] 오류 127
make[1]: 디렉터리 '/home/leegangtoe/pl2016/assignments/00' 나감
Makefile:9: 'all' 타겟에 대한 명령이 실패했습니다
make: **\* [all] 오류 2

와 같은 message가 뜨는데 어떻게 해야하나요?

**Comment by jeehoonkang** [comment]
- "그래서 cygwin의 bin폴더에 coq_makefile을 넣고 make 명령어를 실행했습니다.": 이러지 말고 `PATH` variable을 설정해야 합니다.  `~/.bashrc` 파일에 다음 줄을 넣어보세요:
  
  ```
  export PATH=[Coq이_설치된_폴더]:$PATH
  ```
- Coq이 설치된 폴더에는 `coq_makefile`도 있고 `coqc`도 있습니다.  그래서 `PATH`를 설정하고 나면 `make`가 잘 될겁니다.

**Comment by jeehoonkang** [comment]
Coq이 설치된 폴더는 아마:
- `/Applications/CoqIDE_8.4pl5.app/Contents/Resources/bin/`
- `/usr/local/bin`

중에 하나일 것으로 예상합니다.  이곳에 `coq_makefile`, `coqc`가 있는지 찾아보세요.

**Comment by jeehoonkang** [comment]
문제가 여전히 남아있나요?

**Comment by leegangtoe** [comment]
윈도우에서는 해결을 못해서 vm으로 리눅스를 사용하고 있습니다.

**Comment by jeehoonkang** [comment]
Windows용 매뉴얼을 만들었습니다: https://github.com/snu-sf-class/pl2016#coq

**Comment by jeehoonkang** [comment]
Windows 관련 질문은 https://github.com/snu-sf-class/pl2016/issues/16 에 병합하겠습니다.
