### ISSUE TITLE
Windows에서 숙제를 어떻게 하는것인가요? 

### ISSUE THREAD

**Issue by AlexSeongJu-sr** [snu-sf-class/pl2016#16]
제가 정말 초보라서 질문드립니다. 

예를들어 숙제 1번에서 함수를 정의했다고 친다면,

그럼, example에서 뭘 하라는 것인가요? 함수를 정의했으면 거기에 값을 넣었을 때,

어떤 값이 대응해서 나오는 게 함수라고 알고있는데, 이 문제에서 요구하는 것은 

그 값을 내가 입력해놓고, 그게 맞는지 아닌지 proof하라는 것인가요?

그리고 만약 그렇다면 그 proof가 맞게 이루어졌는지를 compile에서 make로 확인하는 것인가요?

make로 어떻게 확인하면 되나요?

make와 make eval이 어디에 어떤식으로 쓰이게 되는지 모르겠습니다.

**Comment by jeehoonkang** [comment]
- 네 증명하라는 이야기입니다.
- 예 `make`, `make eval` compile 성공하면 증명이 잘 된 것입니다.

**Comment by jeehoonkang** [comment]
- 문제가 여전히 남아있나요?
- 보다 구체적으로 문제상황을 말씀해주시면 더 자세히 답변드리겠습니다.

**Comment by AlexSeongJu-sr** [comment]
예 make, make eval을 ide에서 어떻게 하는지 모르겠습니다. 저번에 랩수업때 봤었는데, 기억도 잘안나고 그때는 coq ide가 아니라 다른걸로 하셨었던것 같은데, coq ide에서 어떻게 make와 make eval을 하는것인가요? 일단 어떻게 수행하는 지 모르겠습니다. 그리고 이것을 왜 수행하는지, 각각의 이유도 잘 모르겠습니다. make와 make eval의 차이가 무엇인가요? 제가 이해하기로는 make는 proof를 검사하는 것이고, make eval은 make가 잘 되었는지 검사하는 것 같은데 맞나요? 
하여튼 ide에서 둘다 어떻게 수행하는 지 모르겠습니다. 만약 TA시간을 알려주신다면 노트북을 들고 찾아가겠습니다.

**Comment by jeehoonkang** [comment]
@djflstkddk 
- `make`은 제출할 파일들을 컴파일하는 것이고,
- `make eval`은 채점하는 것입니다.
- `make`, `make eval`은 CoqIDE에서 하는게 아니라, 터미널에서 하셔야 합니다.
- 작업 환경 (OS, 버전, ...) 등을 알려주시면 문제를 같이 해결하는데 도움이 될 것 같습니다.

**Comment by AlexSeongJu-sr** [comment]
터미널이 무엇인가요? 저는 윈도우 7을 쓰고있습니다. 찾아보니 cygwin을 깔라고 하셨는데 문제가 많은가봅니다. 하여튼 깔아보겠습니다.

**Comment by jeehoonkang** [comment]
- 제가 방금 Windows용 매뉴얼을 만들었습니다: https://github.com/snu-sf-class/pl2016#coq
- 혹시 이대로 따라해보시겠습니까?

**Comment by AlexSeongJu-sr** [comment]
대단히 감사합니다. 따라해보겠습니다.

**Comment by AlexSeongJu-sr** [comment]
export PATH=[Coq이_설치된_폴더]:$PATH 를 bashrc파일에 넣으라고 하셨는데, 제가 초보라서 bashrc파일을 어떻게 여는 지 모르겠습니다. 알려주시면 감사하겠습니다. 메모장으로 여는 것은 아닌거같은데 말입니다.

**Comment by jeehoonkang** [comment]
"For Cygwin, find the file in `C:\cygwin\home\[USER_ID]`."

**Comment by jeehoonkang** [comment]
메모장 등 아무 에디터로 열면 됩니다.  (https://atom.io/ https://www.sublimetext.com/ ...)

**Comment by AlexSeongJu-sr** [comment]
감사합니다. 또 여쭤볼 것이, 터미널에서 make를 수행하라고 하셨는데, p숫자.v 파일을 터미널로 드래그하여 넣어서 make를 치는것인가요? p파일을 어떻게 터미널과 연관시켜서 make를 수행하는 지 잘 모르겠습니다. // 찾아보니 gcc를 설치해서 컴파일하는 것 같네요. 더찾아보겠습니다.

**Comment by jeehoonkang** [comment]
- `make`: 터미널에서 숙제 디렉토리로 이동한 후 "make"라고 넣고 엔터 치시면 됩니다.
- "터미널"에 대해서는: https://github.com/snu-sf-class/pl2016#coq

**Comment by AlexSeongJu-sr** [comment]
.bashrc 파일을 sublime text로 열어서 맨 마지막줄에 
샾 export PATH=$PATH:[/cygdrive/c/Program\ Files\ (x86)/Coq/bin/]
라고 붙였습니다.
그다음 cygwin을 실행하여 which coqc를 치니

which: no coqc in (/usr/local/bin:/usr/bin:/cygdrive/c/Program Files (x86)/NVIDI                       A Corporation/PhysX/Common:/cygdrive/c/Windows/system32:/cygdrive/c/Windows:/cyg                       drive/c/Windows/System32/Wbem:/cygdrive/c/Windows/System32/WindowsPowerShell/v1.                       0:/cygdrive/c/Program Files (x86)/Intel/OpenCL SDK/2.0/bin/x86:/cygdrive/c/Progr                       am Files (x86)/Intel/OpenCL SDK/2.0/bin/x64:/cygdrive/c/Program Files (x86)/Skyp                       e/Phone:/cygdrive/c/Program Files (x86)/QuickTime/QTSystem:/cygdrive/c/Program F                       iles (x86)/Intel/OpenCL SDK/2.0/bin/x86:/cygdrive/c/Program Files (x86)/Intel/Op                       enCL SDK/2.0/bin/x64:/cygdrive/c/Program Files (x86)/NVIDIA Corporation/PhysX/Co                       mmon:/cygdrive/c/Windows/system32:/cygdrive/c/Windows:/cygdrive/c/Windows/System                       32/Wbem:/cygdrive/c/Windows/System32/WindowsPowerShell/v1.0:/cygdrive/c/Program                        Files (x86)/Intel/OpenCL SDK/2.0/bin/x86:/cygdrive/c/Program Files (x86)/Intel/O                       penCL SDK/2.0/bin/x64:/cygdrive/c/Program Files (x86)/Skype/Phone:/cygdrive/c/Pr                       ogram Files (x86)/QuickTime/QTSystem:/cygdrive/c/Program Files (x86)/Intel/OpenC                       L SDK/2.0/bin/x86:/cygdrive/c/Program Files (x86)/Intel/OpenCL SDK/2.0/bin/x64:/                       cygdrive/d:/cygdrive/c/Program Files (x86)/ESTsoft/ALSee/x64:/usr/lib/lapack:[/c                       ygdrive/c/Program Files (x86)/Coq/bin/])
이라고 뜹니다. 무엇이 잘못된것일까요?

**Comment by jeehoonkang** [comment]
대괄호 빼셔요
