### ISSUE TITLE
숙제 제출 페이지가 안열립니다.

### ISSUE THREAD

**Issue by qwerwy1019** [snu-sf-class/pl2016#18]
혹시 학교 밖에서는 접속이 안되나요?

**Comment by k32l** [comment]
The submission link for assignments is not working. It is not working outside the campus as well

**Comment by jeehoonkang** [comment]
- 숙제 1이 나오기 전까지는 서버가 다소 불안정하게 운영될 예정입니다.  죄송합니다.
- 지금까지 숙제 제출 페이지는 디버그 모드에서 돌고 있었는데, 제가 연구실 컴퓨터를 꺼트리는 바람에 서버가 꺼졌었습니다.  조만간 복구하겠습니다.

**Comment by jeehoonkang** [comment]
일단 복구했습니다.

**Comment by k32l** [comment]
Would you mind to write in English?

**Comment by jeehoonkang** [comment]
Sorry for inconvenience.  Hope now all the problems resolved.
