### ISSUE TITLE
Error in submission page

### ISSUE THREAD

**Issue by Ailrun** [snu-sf-class/pl2016#19]
When I submit my HW,

Server said,

RETCODE: 2

STDOUT:
(echo "-I ."; \
         echo D.v P01.v P02.v P03.v E01.v E02.v E03.v) > _CoqProject
coq_makefile -f _CoqProject -o Makefile.coq

STDERR:
make: coq_makefile: Command not found
make: **\* [Makefile.coq] Error 127

Is this my fault, or is there any problem with server?

**Comment by jeehoonkang** [comment]
Sorry for inconvenience.  Hope now all the problems resolved.

The problem is that `coq_makefile` is installed via `opam` in the evaluation server.  But I changed the shell recently, and the opam initialization script is not executed.  I inserted the script in my rc file.
