### ISSUE TITLE
윈도우에서 check.sh 는 어떻게 봐야 하나요? ㅠ

### ISSUE THREAD

**Issue by wjdtmdrms** [snu-sf-class/pl2016#23]
문제 푼 후에 컴파일, 메이크를 모두 다 성공했습니다.

그 후에 check.sh 를 돌려서 확인해보려 했는데 커맨드창이 열리고 0.5초만에 닫혀버리네요 ㅠ

인터넷 검색해서 window powershell 에서 ./check.sh > a.txt 명령어를 줬는데

열어보니 텅텅 비어있더라구요.

윈도우에서 어떻게 확인해야 하는지 궁금합니다.

**Comment by taehwoi** [comment]
파워쉘에서는 sh check.sh 을 하면 된다고 하네요. 깃을 까시면 sh도 같이 설치된다고 합니다.

**Comment by shuuki4** [comment]
저는 cygwin을 쓰긴 했는데, cygwin에서는 sh check.sh로 check.sh가 돌아가긴 하는데 에러가 나더라구요. 그래서 dos2unix를 받아서 dos2unix check.sh 하고 다시 check.sh를 돌리니 그 이후로는 정상적으로 작동했습니다

**Comment by jeehoonkang** [comment]
- Related: #13
- @shuuki4 리파지토리에 있는 파일들은 모두 Unix linebreak로 인데, dos2unix가 왜 필요한지 궁금합니다.  혹시 Git으로 다운로드 받을 때 DOS 포맷으로 바뀌어 저장되나요?
- @indiofish 좋은 정보 감사합니다.  사실 제가 Windows에서는 cygwin을 깔아서 하는 방법밖에 테스트해보지 않았습니다.  어떤 분이시라도 Windows에서 IDE로 숙제 하고 제출하는데까지 성공하셨다면, 그 성공담을 공유해주시면 정말 감사하겠습니다.

**Comment by shuuki4** [comment]
@jeehoonkang clone 한 직후에 파일 포맷을 봤는데, 전부 DOS 포맷으로 되어있었습니다. 말씀하신대로 Git Shell에서 받을 때 자동으로 DOS 포맷으로 바뀌는 것 같습니다. 제가 따로 설정을 건드린 기억은 없어서, 아마 기본적으로 설정이 이렇게 되있지 않나 싶네요..

**Comment by jeehoonkang** [comment]
말씀해주신 이슈는 모두 README에 반영하였습니다.  소중한 의견 감사드립니다.

**Comment by taehwoi** [comment]
mac에서는 sh가 bash인데 linux에서는 sh로는 check.sh를 실행할 수 없는 것 같습니다.

**Comment by jeehoonkang** [comment]
@indiofish CentOS 7에서는 `sh ./check.sh`가 잘 되어서 커밋했는데, 잘 안되는 환경이 있나보네요.
- 혹시 어떤 환경에서 하셨는지 알려주실 수 있으십니까?
- 에러메시지가 있었다면 혹시 알려주실 수 있으십니까?

**Comment by taehwoi** [comment]
우분투 14.04입니다.
`sh ./check.sh`을 하면 `./check.sh: 3: ./check.sh: Syntax error: "(" unexpected`가 출력됩니다.
`bash ./check.sh`을 하면 잘 실행됩니다.
CentOS에서는 sh 가 bash로 symlink되어 있다는 것 같습니다.

**Comment by jeehoonkang** [comment]
@indiofish "파워쉘에서는 sh check.sh 을 하면 된다고 하네요. 깃을 까시면 sh도 같이 설치된다고 합니다.": 죄송합니다만, 혹시 Git을 깔면 `bash`도 설치되는지도 여쭤봐도 될까요?  그럼 `Makefile`에서 `bash ./check.sh`를 실행하도록 고칠 예정입니다.

**Comment by taehwoi** [comment]
네 bash로도 잘 되는 것 같습니다.

**Comment by jeehoonkang** [comment]
Windows용 매뉴얼을 만들었습니다: https://github.com/snu-sf-class/pl2016#coq
