### ISSUE TITLE
윈도우에서는 make, make eval, make submission 어떻게 하나요?

### ISSUE THREAD

**Issue by wjdtmdrms** [snu-sf-class/pl2016#24]
깃에는 위의 것들을 다 한 후에 제출하라고 돼 있는데

윈도우에서는 어떻게 돌려야 하는건질 모르겠네요 ㅠ

**Comment by AlexSeongJu-sr** [comment]
저도 이게 궁금합니다. 랩수업때는 분명 make make eval이 가능했었는데, 윈도우는 뭔가 다른건가요? coq ide가 실행이 되면 되는건가요? make와 make eval을 어떻게 돌리는 지 모르겠습니다.
