### ISSUE TITLE
과제1-7에서 vacuous proof를 시도하시는 분들

### ISSUE THREAD

**Issue by wortgg** [snu-sf-class/pl2016#29]
이 때 Inversion 사용하시면
추가적으로 보조 정리를 증명할 필요없이 
명제를 증명가능합니다!

**Comment by jeehoonkang** [comment]
On inversion:
- https://www.cis.upenn.edu/~bcpierce/sf/current/MoreCoq.html#lab162
- https://coq.inria.fr/refman/Reference-Manual010.html#inversion
