### ISSUE TITLE
Addition and Multiplication in COQ

### ISSUE THREAD

**Issue by Ailrun** [snu-sf-class/pl2016#3]
I want to reproduce the proof of summation from 1 to n, so I try it, but in the middle of the proof I was stuck because of some basic(?) rules, like commutative, associative, n + 0 = n, and so on.
These are too many to prove one by one, and based on my memory, professor's proof is very simple and clear.
I found some "Standard libraries", but the only thing with commutative rule is obsolete one. (https://coq.inria.fr/library/Coq.Arith.Plus.html) and there is no such things in currently valid one. (https://coq.inria.fr/library/Coq.Arith.PeanoNat.html)

Is there any easy way to deal with addition and multiplications with those stuff?

**Comment by jeehoonkang** [comment]
- Please consult the Coq 8.4pl5 documentation: https://coq.inria.fr/distrib/V8.4pl5/files/Reference-Manual.pdf
- CoqIDE and Emacs supports lookup of relevant definitions.  For Emacs, `C-c C-a C-a nat` will give you all the definitions about `nat`.  Maybe it helps you to find the lemma you want.

**Comment by Ailrun** [comment]
Thank you for your kindness. Sorry for bothering you

**Comment by jeehoonkang** [comment]
TA is for _you_.  Please keep asking..!

I would like to create a FAQ page based on the questions students asked.  There I will write down some doc on finding lemmas.  Until then I will keep this issue open.

**Comment by jeehoonkang** [comment]
This will list up all the definitions related to `nat`:

```
Require Import NArith.

SearchAbout nat.
```
