### ISSUE TITLE
제출을 눌리면 Server Error(500)

### ISSUE THREAD

**Issue by kimshinhwi** [snu-sf-class/pl2016#30]
과제를 제가 수정한 P01.v~P07.v만 모아서 압축하고
제출하는 페이지에 가서 submit을 눌럿는데,
Server Error(500)만 뜹니다....
# 도와줍쇼 ㅜㅜ

아 그리고 제출페이지 아이디 비번은 만들어져있던데,
여기 github?아이디는 제가 만드는게 맞나요?.
글올리고 싶어서 제가 만들었는데.
이거에 대한 내용을 들은것같은데 기억이 잘안나서 ..죄송합니다.

**Comment by jeehoonkang** [comment]
일단 GitHub 아이디는 본인이 만드신게 맞습니다.

**Comment by jeehoonkang** [comment]
제 파일들을 제출해보니 잘 되는데, 혹시 안되는 submission zip 파일을 pl2016@sf.snu.ac.kr 로 보내주시면 확인해보겠습니다.

**Comment by kimshinhwi** [comment]
네 ㅎㅎ 지금 보냈습니다.

**Comment by jeehoonkang** [comment]
문제가 발생하는 것을 확인했습니다.  곧 처리해서 답변드리겠습니다.

**Comment by jeehoonkang** [comment]
- 왜인지 모르겠지만, `__MACOSX`라는 폴더만 빼면 제출이 잘 되는 것 같습니다.
- 일단 빼고 제출해주시겠어요?
- 서버에서 나타나는 문제는 곧 해결하겠습니다.

**Comment by jeehoonkang** [comment]
- Aㅏ.. 왜인지 development server에서는 문제가 안나타나고, production server에서만 나타나네요.  문제 해결에 생각보다 어려움이 있을 수도 있겠습니다.
- 보내주셨던 zip 파일이 `make submission`을 통해 나온건가요?  아니면 직접 zip하셨습니까?

**Comment by kimshinhwi** [comment]
제가 직접 zip했는데...ㅎ
make submission을 통해 나왔다는게 무슨소린지 잘.. 모르겠습니다.
그냥 코드를 다 짜고 P01.v 부터 P07.v만 모아서 제가 zip해서 낸건데 .ㅎ

**Comment by jeehoonkang** [comment]
README를 다시 읽어주셔요.

**Comment by kimshinhwi** [comment]
아..그냥 압축파일이름을 영어로 바꾸니까 되네요....
readme에는 제가 영어를 못해서 그런지 못찾겠네요 ㅎ.ㅎ.
그래도 다행히 해결했습니다 .감사합니다.

**Comment by jeehoonkang** [comment]
- 한글을 쓴 문제이군요  . . . . . 버그를 찾아주셔서 감사합니다.
- 다만 제가 지금 문제를 해결하기가 어렵습니다.  일단 README에 영어/숫자로만 된 파일을 제출하라는 이야기를 써 놓았습니다.

감사합니다.
