### ISSUE TITLE
Can I use Require Export in assignment?

### ISSUE THREAD

**Issue by shuuki4** [snu-sf-class/pl2016#32]
Assignment 2에서 앞서 증명한 Theorem을 사용하려고 하는데, 파일이 별개로 되어있어서 불러올 수가 없습니다.
앞선 파일에서 증명한 것을 들고 오기 위해 Require Export 문을 사용해도 되는건가요?

**Comment by jeehoonkang** [comment]
-  `Require Export`는 쓰지 마셔요.
- `make eval`로는 걸러낼 수 없는데, 서버에서는 걸러내고 있습니다. . .

**Comment by shuuki4** [comment]
@jeehoonkang 그러면 증명한걸 복붙해서 다시 쓰는 것 이외에 불러와서 쓰는 방법은 없는건가요? ㅜ.ㅜ

**Comment by jeehoonkang** [comment]
네.. ㅠ

**Comment by k32l** [comment]
I didn't get. So we should write all the proved theorem again if we want to use them in the code?

**Comment by jeehoonkang** [comment]
@k32l Yes you should.  It is a little bit clumsy to copy-and-paste lemmas, but please consider that it is essential for automatic evaluation..
