### ISSUE TITLE
숙제에서 Case "!@###". 사용할 수 있도록 해주시면 안될까요?

### ISSUE THREAD

**Issue by LeeGyeongGeon** [snu-sf-class/pl2016#36]
물론 교수님께서 Case "@$#%@%".를 선호하시지 않는 것 같지만.. 그래서 저도 안 쓰려고 노력을 합니다만

sf 기본 파일로 공부를 하다가 Theorem들을 숙제에 붙여넣을 때마다 Case 문을 다 지우려니 너무 번거로운 것 같아 요청을 드려봅니다.

**Comment by jeehoonkang** [comment]
직접 정의해서 쓰셔도 좋습니다: https://github.com/snu-sf-class/pl2016/blob/master/sf/SfLib.v#L40
