### ISSUE TITLE
예컨데 `plus_n_O`같은 lemma를 써도 될까요?

### ISSUE THREAD

**Issue by hoony** [snu-sf-class/pl2016#37]
다른 파일에서 증명한 Theorem을 쓰고 싶으면 그 증명 코드를 복붙해서 써야 한다고 말씀하셨는데
증명한 Theorem 코드를 복붙 안하고 쓸 경우 
Error: The "Theorem이름" was not found in the current enviroment.
와 같은 에러가 나는 경우도 있지만
" plus_n_O "와 같은 Theorem은 증명한 코드를 복붙 안하고 다른 파일에서 사용해도 에러 없이 잘 돌아갑니다.
그 이유가 궁금합니다.
그리고 이럴 경우엔 그냥 복붙 안하고 사용해도 채점에 별 문제가 없는지도 궁금합니다.

**Comment by jeehoonkang** [comment]
- Standard library에서 정의된 것중 아무것도 import 안해도 쓸 수 있는 정의들이 있습니다.  `plus_n_O`가 그런 것들인듯 합니다.
- 예 상관 없으리라 생각합니다.  서버에서 뜬 점수를 인정해드리겠습니다.
- 서버는 곧 띄우겠습니다.

**Comment by k32l** [comment]
I wrote plus_n_O from the book inside my code, because IDE was given error and I just left it. Is it okay?

**Comment by jeehoonkang** [comment]
@k32l Not sure what you meant, but if evaluation server says it's okay, it's indeed okay.
