### ISSUE TITLE
Question about Fixpoint

### ISSUE THREAD

**Issue by k32l** [snu-sf-class/pl2016#40]
The function [split] is the right inverse of combine: it takes a
    list of pairs and returns a pair of lists. 

Fixpoint split
           {X Y : Type} (l : list (X*Y))
           : (list X) \* (list Y) :=
  match l with
    | nil => (nil, nil)
    | (x, y) :: t => (x :: fst (split t), y :: snd (split t))
  end.

On the line  | (x, y) :: t => (x :: fst (split t), y :: snd (split t)). As I understood when l is a list, where (x , y) is a pair, then in tail t we have a nil? Then on line (x :: fst (split t), y :: snd (split t)) what is inside t?

**Comment by taehwoi** [comment]
I think (x, y) :: t would first be matched as head :: tail, head being the first element of the list and tail the rest of it.
Since the first element happens to be a pair, we can further match it to (x, y) :: tail. 

``` ocaml
[(1, 2), (3, 4), (5, 6)]
(1 :: fst(split ([(3, 4), (5, 6)]), 2 :: snd(split([(3, 4), (5, 6)])) 
```

**Comment by k32l** [comment]
Output should be like this : Example test : split [(1, 2); (3, 4)] = ([1;3], [2;4])
(1 :: fst (split ([(3, 4)]), 2 :: snd(split([(3, 4)]))
(1 :: fst (3 :: fst (split nil), 2 :: snd(4 :: snd (split nil))
and then 
((1 :: fst (3 :: fst (nil, nil), 2 :: snd(4 :: snd (nil, nil)))
((1 :: fst (3 :: (nil), 2 :: snd(4 :: nil))
((1 :: 3 ), (2 :: nil )
Did I make mistake somewhere?

**Comment by k32l** [comment]
Output should be like this : Example test : split [(1, 2); (3, 4)] = ([1;3], [2;4])
(1 :: fst (split ([(3, 4)]), 2 :: snd(split([(3, 4)]))
(1 :: fst (3 :: fst (split nil), 2 :: snd(4 :: snd (split nil))
and then 
((1 :: fst (3 :: fst (nil, nil), 2 :: snd(4 :: snd (nil, nil)))
((1 :: fst (3 :: (nil), 2 :: snd(4 :: nil))
((1 :: 3 ), (2 :: nil )
Did I make mistake somewhere?

**Comment by taehwoi** [comment]
``` ocaml
(1 :: fst (3 :: fst (split nil), 2 :: snd(4 :: snd (split nil))
```

this line should be

``` ocaml
(1 :: (3 :: fst(split(nil))), 2 :: (4 :: snd(split nil)))
```

fst and snd is already applied to split([3, 4]) in your example.

**Comment by k32l** [comment]
(1 :: fst (split ([(3, 4)]), 2 :: snd(split([(3, 4)]))
(1 :: fst (3 :: fst (split nil),4 :: snd (split nil)), 2 :: snd(3 :: fst (split nil),4 :: snd (split nil)))
and then 
(1 :: fst (3 :: fst (split nil),4 :: snd (split nil)), 2 :: snd(3 :: fst (split nil),4 :: snd (split nil)))
(1 :: fst (3 :: fst (nil, nil),4 :: snd (nil, nil)), 2 :: snd(3 :: fst (nil, nil),4 :: snd (nil, nil)))
(1 :: fst (3 :: nil),(4 ::nil)), 2 :: snd(3 :: nil),(4 :: nil)))
(1 :: 3 ),(4 ::nil)), (2 :: nil),(4 :: nil)))
So confused

**Comment by taehwoi** [comment]
``` ocaml
(1 :: fst (3 :: nil),(4 ::nil)), 2 :: snd(3 :: nil),(4 :: nil)))

(*
fst( (3 :: nil), (4 :: nil) ) == 3::nil
snd( (3 :: nil), (4 :: nil) ) == 4::nil
*)
((1 :: 3 :: nil), (2 :: 4 :: nil))
```

**Comment by k32l** [comment]
@indiofish Thank you a lot!

**Comment by indiofish** [comment]
Personally, I think it would be easy to reason about Fixpoints if you just believe that split works well for smaller cases.
If we believe that split(t) works well at case (x, y) :: t => (x :: fst (split t), y :: snd (split t))
we can see that split(l) will also work well since they append x and y to a pair of lists.
