### ISSUE TITLE
Assignment 02. Problem 9. Error: The reference natprod

### ISSUE THREAD

**Issue by k32l** [snu-sf-class/pl2016#41]
I get the Error: The reference natprod was not found in the current environment. Can I insert Inductive type definition for natprod into the code and swap_pair as well?

**Comment by k32l** [comment]
Are we allowed to insert notations into the code as well?

**Comment by jeehoonkang** [comment]
`natprod` is defined in `D.v`:

```
Inductive natprod : Type :=
  pair : nat -> nat -> natprod.
```
- Did you remove `Require Export D.`?

**Comment by jeehoonkang** [comment]
You can insert notations in `P??.v` files.

**Comment by k32l** [comment]
No I didn't, but in the IDE it is not working. Even after I do make

**Comment by jeehoonkang** [comment]
Check if definitions in `D.v` is in the environment.  For e.g., `Check natprod.` will let you know whether `natprod` is defined in the environment or not.

**Comment by k32l** [comment]
No, it is not defined. And for " Require Export D. " it gives me "Error: Compiled library D.vo makes inconsistent assumptions over library
Coq.Init.Notations
"

**Comment by k32l** [comment]
So I have to erase "Require Export D." then do coding. Compile if it works. And then put "Require Export D." again into the code, because it is not compiling with it

**Comment by jeehoonkang** [comment]
I guess your IDE and shell have different versions of Coq.
- What is the version of IDE?
- What is the result of `coqc --version` in the shell?

If they mismatch, please read and follow the manual.

**Comment by k32l** [comment]
yes...it is different 8.4pl6. But you helped me to install it

**Comment by k32l** [comment]
Do I need to add the directory that contains Coq binaries in the PATH variable?

**Comment by jeehoonkang** [comment]
yes

**Comment by k32l** [comment]
I reinstalled IDE. And for coqc --version it says "-bash: coqc: command not found"

**Comment by jeehoonkang** [comment]
Make sure that your `PATH` variable contains the directory that contains `coqc` and `coqtop`.

**Comment by k32l** [comment]
I changed the path. And when I type coqc --version it shows 8.4pl5. But if I close and open terminal and type coqc --version again it says "-bash: coqc: command not found". How to save the PATH?

**Comment by jeehoonkang** [comment]
https://github.com/snu-sf-class/pl2016#coq

**Comment by jeehoonkang** [comment]
Please read the fine manual.

**Comment by k32l** [comment]
I installed coq

**Comment by k32l** [comment]
I edited .bashrc file but still it is not working

**Comment by jeehoonkang** [comment]
- Do you use `bash`?
- Is `.bashrc` your init file?  Did you check `.bash_profile` or other files?

**Comment by k32l** [comment]
I checked for ~/.bashrc and wasn't there, so I made it by vim .bashrc and put PATH there

**Comment by k32l** [comment]
What do you mean by using bash?

**Comment by jeehoonkang** [comment]
- What is you shell? bash? zsh? or other shells?
- What init file your shell uses?  I guess it is `~/.bashrc`, but your configuration seems different from it.
- If initializing the `PATH` variable doesn't work, at least you can type `export PATH=...` every time you want to compile..
