### ISSUE TITLE
D.v 파일 관련해서 에러가 있어 문의합니다 ㅠ

### ISSUE THREAD

**Issue by wjdtmdrms** [snu-sf-class/pl2016#42]
![image](https://cloud.githubusercontent.com/assets/17424637/13944701/d1a35b94-f04a-11e5-9240-3359bdb40236.png)

윈도우 coq 쓰고 있구요..
git pull 해서 ass02 를 받았는데 뭘 입력해도 계속 저 에러가 뜨네요..
D.v 파일도 정상적으로 있는데 원인이 뭘까요? ㅠ

**Comment by jeehoonkang** [comment]
`make` 한번 해보세요.

**Comment by wjdtmdrms** [comment]
감사합니다~

**Comment by wjdtmdrms** [comment]
숙제 제출 사이트 로그아웃 됐는데 비밀번호가 기억이 안 납니다 ㅠㅠ

**Comment by jeehoonkang** [comment]
@wjdtmdrms pl2016@sf.snu.ac.kr 로 연락 주셔요.
