### ISSUE TITLE
과제 관련 두가지 질문이 있습니다.

### ISSUE THREAD

**Issue by kimdawn** [snu-sf-class/pl2016#45]
1. 과제 2번 P06.v을 보면 Use assert to help prove this theorem if necessary. You shouldn't need to use induction. 이라는 문구가 있어서 혹시나 해서 여쭤보는데 induction이 아니라 꼭 assert를 이용하여 증명해야 하는 건가요? 
2. 과제 딜레이를 한 경우 적용되는 페널티는 한 문제마다 적용되나요. 아니면  과제 전체로 적용되나요? 예를 들어 데드라인 전에 과제1 1~6번을 딜레이 전에 다 증명해서 60점을 받고 데드라인 넘긴 날에 7번을 풀어 새로운 submission.zip을 업로드 하면 최종 점수는 60+8 인지 아니면 과제 전체가 딜레이로 판단되어 56점을 받는지 궁금합니다.

**Comment by jeehoonkang** [comment]
- 꼭 `assert`를 이용해 증명할 필요는 없습니다.  다만 이 기회에 `assert`가 뭐 하는 tactic인지 확인하고 넘어가보시기 바랍니다.
- 딜레이에 관해: 교수님께 여쭤보겠습니다.  좋은 질문 감사합니다.

**Comment by jeehoonkang** [comment]
페널티는 문제마다 적용됩니다.  곧 서버를 수정하고 공지하겠습니다.

**Comment by kimdawn** [comment]
답변 감사합니다!
