### ISSUE TITLE
Assignment 03. P01.V

### ISSUE THREAD

**Issue by k32l** [snu-sf-class/pl2016#47]
In the comments to the problem it is said (*\* Complete the definitions of [nonzeros], [oddmembers] and
[countoddmembers] below. Have a look at the tests to understand what these functions should do. *).  But in the actual problem there is  only given nonzeros and example for it. Should we do [oddmembers] and [countoddmembers], even though they are not given and there are no Examples for them?

**Comment by jeehoonkang** [comment]
You can safely ignore the instructions on `oddmembers` and `countoddmembers`.  Define `nonzeros`, and prove `nonzeros_app`, and then `make eval`.  If it works, then your submission will be fine.
