### ISSUE TITLE
[Windows cygwin 사용자] ./check.sh: line2: $'\r': command not found

### ISSUE THREAD

**Issue by aqjune** [snu-sf-class/pl2016#48]
혹시나 같은 문제를 만나신 분들께 도움이 될 수 있을까 해서 글을 남겨두어요.

Windows에서 cygwin을 이용해서 make를 하시면 아래와 같은 에러가 날 수 있습니다..!

![image](https://cloud.githubusercontent.com/assets/6484889/14064647/7f41f71c-f445-11e5-9a43-8ee16d42f5da.png)

이 때에는 터미널에서 `dos2unix check.sh` 명령어를 입력하시면 됩니다.

아래는 dos2unix를 cygwin에서 설치하는 장면입니다.

![image](https://cloud.githubusercontent.com/assets/6484889/14064650/cf7c06dc-f445-11e5-91b0-f5ffe5ea45de.png)

**Comment by jeehoonkang** [comment]
Thank you so much!
