### ISSUE TITLE
과제제출사이트 아이디랑 비밀번호?

### ISSUE THREAD

**Issue by AlexSeongJu-sr** [snu-sf-class/pl2016#49]
죄송한데 TA시간에 들었는데 기억이 안나서 여쭤봅니다.
아이디랑 비밀번호가 무엇인가요?
학번으로 하면 되나요? 학번에 -(다시) 붙이나요?
과제 폴더를 압축해서 압축파일을 제출하면 되는 것인가요?

감사합니다.

**Comment by AlexSeongJu-sr** [comment]
학번에 -붙여서 아이디 비밀번호 입력해도 접속이 안됩니다.

**Comment by jeehoonkang** [comment]
- 예컨데 학번이 2013-12345라면, 초기 아이디 / 비번은 2013-12345 / 2013-12345 입니다.
- 계속 문제가 있는 경우 학번 적어서 이메일 보내주시면 비번 바꿔 알려드리겠습니다.

**Comment by jeehoonkang** [comment]
과제는 `make submission`하면 `submission.zip`이 생성됩니다.  그걸 제출하시면 됩니다.  자세한 내용은 매뉴얼을 참조하세요 https://github.com/snu-sf-class/pl2016#assignment

**Comment by AlexSeongJu-sr** [comment]
make submission을 하면 다음과 같이 뜹니다.

make -f Makefile.coq E01.vo E02.vo E03.vo E04.vo E05.vo E06.vo E07.vo E08.vo E09.vo E10.vo
make[1]: 디렉터리 '/cygdrive/d/Desktop/programming/pl2016-master/pl2016-master/assignments/02' 들어감
make[1]: 'E01.vo'은(는) 이미 업데이트되었습니다.
make[1]: 'E02.vo'은(는) 이미 업데이트되었습니다.
make[1]: 'E03.vo'은(는) 이미 업데이트되었습니다.
make[1]: 'E04.vo'은(는) 이미 업데이트되었습니다.
make[1]: 'E05.vo'은(는) 이미 업데이트되었습니다.
make[1]: 'E06.vo'은(는) 이미 업데이트되었습니다.
make[1]: 'E07.vo'은(는) 이미 업데이트되었습니다.
make[1]: 'E08.vo'은(는) 이미 업데이트되었습니다.
make[1]: 'E09.vo'은(는) 이미 업데이트되었습니다.
make[1]: 'E10.vo'은(는) 이미 업데이트되었습니다.
make[1]: 디렉터리 '/cygdrive/d/Desktop/programming/pl2016-master/pl2016-master/assignments/02' 나감
zip submission.zip P??.v
/bin/sh: zip: command not found
Makefile:18: 'submission' 타겟에 대한 명령이 실패했습니다
make: **\* [submission] 오류 127
그래서 그냥 p.v파일들을 압축하여 제출하니 페이지를 표시할수 없다고 뜹니다.

**Comment by jeehoonkang** [comment]
`P01.v`, `P02.v`, ... 파일들만 압축해서 제출하셔요.

**Comment by AlexSeongJu-sr** [comment]
죄송한데 그렇게 해서 제출하니 페이지를 표시할수없다고 뜹니다

**Comment by jeehoonkang** [comment]
- 스크린샷 첨부해줄 수 있나요?
- 제출한 파일 pl2016@sf.snu.ac.kr 로 보내주셔요.

**Comment by AlexSeongJu-sr** [comment]
아 p.v말고 02번폴더를 통째로 압축해서 제출하니 점수가 뜨면서 제출이됩니다
