### ISSUE TITLE
숙제 6에서 induction관련하여 이상한 현상이 발생합니다.

### ISSUE THREAD

**Issue by LeeGyeongGeon** [snu-sf-class/pl2016#57]
안녕하세요. 6번 숙제 중에 induction 관련하여 이상한 현상이 발견되어 질문을 드립니다.

![6_1](https://cloud.githubusercontent.com/assets/11293091/14419867/9e10ecc4-0003-11e6-8dfe-d44015a6a8ae.png)

![6_2](https://cloud.githubusercontent.com/assets/11293091/14419866/9e10da90-0003-11e6-949a-3cbd7268e4db.png)

위 사진은 martini server에서 sf 기본 파일상에서 작업을 하는 과정입니다. induction을 하면 자연스럽게 n이라는 변수에 대해 induction이 진행되고, 아래에서는 induction hypothesis가 발생하여 증명을 마칠 수 있습니다.

![6_3](https://cloud.githubusercontent.com/assets/11293091/14419868/9e13fc66-0003-11e6-9711-03bee7d77011.png)

그런데 숙제를 같은 서버에서 하게 되면 induction을 했을 때에 엉뚱하게 n0라는 변수가 도입되어 더 이상 증명이 불가능해집니다.. 이런 상황에서는 어떻게 해야 할까요?

**Comment by alxest** [comment]
혹시 둘이 콕 버전은 같은가요?

**Comment by LeeGyeongGeon** [comment]
같은 마티니 서버에서 실행했기 때문에 coq 버젼은 같다고 봐야 할 것 같습니다.

**Comment by alxest** [comment]
1. Set Printing All. 을 쓰고 theorem 으로 들어가보니, 두 경우 모두 

```
   forall n m : nat, le (S n) m -> le n m
```

꼴로 나타남을 알 수 있습니다.
2. le 가 두 경우에 같은 정의인지 확인해봅시다. Require Export D 전후로 Print le. 를 해보면,
Require Export D. 전

```
Inductive le (n : nat) : nat -> Prop :=  le_n : n <= n | le_S : forall m : nat, n <= m -> n <= S m
```

Require Export D. 후

```
Inductive le : nat -> nat -> Prop :=  le_n : forall n : nat, n <= n | le_S : forall n m : nat, n <= m -> n <= S m
```

사용된 induction principle도 
Print le_ind. 를 해보면 두 경우에 다릅니다.

**Comment by jeehoonkang** [comment]
- 문제가 여전히 남아있나요?
- 아닌 경우, close해주시면 감사하겠습니다.
