### ISSUE TITLE
apply 관해 질문드립니다.

### ISSUE THREAD

**Issue by leehyukgi** [snu-sf-class/pl2016#58]
제가 apply를 제대로 이해하지 못한 것 같아서 질문 좀 드릴게요 ㅠㅠ

![1](https://cloud.githubusercontent.com/assets/8819817/14432249/450fea80-0044-11e6-858b-3001d8eafa5c.png)
위와 같은 코드에서
![2](https://cloud.githubusercontent.com/assets/8819817/14432295/736a2288-0044-11e6-868b-18bfa4936649.png)
apply H2를 하면 ev m 과 ev p로 나뉘는데
![3](https://cloud.githubusercontent.com/assets/8819817/14432307/8864448e-0044-11e6-88d9-38bb5cf8480d.png)
똑같은 형태의 eq1에 apply H2를 했을 때 적용이 되지 않는 이유가 뭔가요?
![4](https://cloud.githubusercontent.com/assets/8819817/14432312/8b707918-0044-11e6-81e1-30b907c6729a.png)
variable a를 n으로 지정해서 apply H2 with (a:=n) 를 적용했을 때, ev(m+p)와는 다른 형태로 쪼개지던데 이건 또 왜 그런지 궁금합니다.

**Comment by jeehoonkang** [comment]
- 일단 코드는 `이렇게` 표현해주시기 부탁드립니다 (https://help.github.com/enterprise/11.10.340/user/articles/github-flavored-markdown/#fenced-code-blocks).
- `H2`의 `b`가 `eq1`의 `n+m`이 되는데, `a`가 뭔지 알 수가 없어서 나는 에러입니다.  `a`가 뭔지 몰라도 tactic을 적용하고 싶으면 `eapply` 해보세요.
- `H2`의 `a`가 `n`, `b`가 `n+m`이 된 셈입니다.  그러면 `H2`의 결론 `ev (a+b)`는 `ev (n+(n+m))`이 됩니다.

**Comment by leehyukgi** [comment]
다음부턴 말씀하신대로 코드 올리겠습니다.
답변 감사드립니다!
