### ISSUE TITLE
windows에서 make하는 법을 모르겠습니다.

### ISSUE THREAD

**Issue by leegangtoe** [snu-sf-class/pl2016#6]
windows에서 make하는 법을 모르겠습니다.

**Comment by jeehoonkang** [comment]
Would you please use cygwin ( https://www.cygwin.com ) to install build tools?

**Comment by jeehoonkang** [comment]
연관된 질문은 댓글로 달아주시면 감사하겠습니다. https://github.com/snu-sf-class/pl2016/issues/15
