### ISSUE TITLE
Assignment 06. P11.v . Error: Tactic failure.

### ISSUE THREAD

**Issue by k32l** [snu-sf-class/pl2016#60]
After I wrote Inductive pal. I tried to check it with the given test:
   Example test_pal_1: pal [0; 1; 0].
   Proof. reflexivity . Qed.

But then I get an error:
   Error:
   Tactic failure: The relation pal is not a declared reflexive relation. Maybe you need to require the Setoid     library.

Why does it happen? How do I check it if it is not reflexive?

**Comment by jeehoonkang** [comment]
You cannot prove it with `reflexivity` tactic.  I guess `constructor` tactic will help you solve the problem.

**Comment by k32l** [comment]
When I use constructor, another error appears:
Error: No applicable tactic.

**Comment by jeehoonkang** [comment]
Try econstructor

**Comment by k32l** [comment]
I tried it. And it says me the same

**Comment by jeehoonkang** [comment]
I believe the problem should be solved by the `econstructor` tactic.  If not, I guess your definition of `pal` needs modification..
If you still have more questions, please visit the TA's office in the TA hour (today 18:15-21:00).

**Comment by jeehoonkang** [comment]
Do you still experience the problem?  If not, please close the issue.
