### ISSUE TITLE
과제 제출 서버가 죽었습니다.

### ISSUE THREAD

**Issue by hestia49** [snu-sf-class/pl2016#69]
과제 7을 제출하고 Running중에 급작스럽게 접속이 불가능해졌으며 다른 PC에서도 접속 불능을 확인하였습니다.
확인 부탁드립니다

**Comment by knockLeopard** [comment]
저도 제출서버가 안들어가지네요...

**Comment by AlexSeongJu-sr** [comment]
저도 그렇습니다.. 어떻게하죠..?

**Comment by jeehoonkang** [comment]
숙제 7의 듀를 2일 늦추겠습니다.  2016년 5월 3일 23:59까지입니다.

**Comment by AlexSeongJu-sr** [comment]
죄송한데 제가 숙제 6의 delay를 제출해야 하는데 그것도 늦춰주실수 있나요? 다했는데 제출을 못하고있습니다

**Comment by jeehoonkang** [comment]
@djflstkddk 예 그렇게 하겠습니다.  마찬가지로 2일 늦추겠습니다.

**Comment by knockLeopard** [comment]
저도 윗분과 마찬가지로 숙제6의 delay를 제출해야하는데 어떻게 해야하는지 여쭤봐도 될까요?

**Comment by jeehoonkang** [comment]
미숙한 운영을 보여드려 정말 죄송합니다.

**Comment by knockLeopard** [comment]
아닙니다 due 임박해서야 내는 제 불찰입니다...

**Comment by AlexSeongJu-sr** [comment]
의문의 1패

**Comment by jeehoonkang** [comment]
복구되었습니다. http://147.46.15.109:9480/

**Comment by hestia49** [comment]
![2016-05-02 12 57 48](https://cloud.githubusercontent.com/assets/14194355/14946932/8ee5750e-1065-11e6-9615-dab5658253b4.png)
 서브밋시 서버 에러가 납니다.

**Comment by jeehoonkang** [comment]
다시 문제 해결했습니다.  혹시 확인 다시 부탁드려도 될까요? @hestia49

**Comment by shuuki4** [comment]
@jeehoonkang 서브밋도 되는것 같습니다. :+1:

**Comment by jeehoonkang** [comment]
Once more, I am sincerely sorry for the clunky operation. Thank you all for your patience.

**Comment by hestia49** [comment]
정상적으로 작동됩니다.
로컬에서는 P02.v가 정상적으로 실행되는데(오랜 시간이 걸립니다)
서버에서는 컴파일 에러가 납니다.

**Comment by Dongjoo-Kim** [comment]
지금 제출해보니 server error(500)이 나오고 제출한 파일은 pending상태에서 바뀌지 않습니다. server status도 확인이 불가능한데 다시 죽은건가요?

**Comment by jeehoonkang** [comment]
- @Dongjoo-Kim 왜인지 모르겠지만, 다시 죽었었습니다.  죄송합니다.
- 문제가 지속되는 원인은 파악중에 있습니다.  이번에는 지난번과 달리 채점서버 가상머신을 재부팅하였고, 문제가 더 없길 기대합니다..
- 보다 구체적으로 원인에 대해 말씀드리면, evaluation task를 처리하기 위해 message queue implementation인 rabbitmq를 사용하는데, rabbitmq server가 자꾸 죽었습니다.
  사용 환경은 다음과 같습니다.  혹시 troubleshooting에 경험이 있으신 분이 있으면 알려주시면 큰 도움이 될 것 같습니다.
  - Hypervisor: SmartOS Live Image v0.147+ build: 20151210T194528Z
  - VM: container-native linux (CentOS 7.2 20160201)
  - rabbitmq-server: installed with `yum`

**Comment by jeehoonkang** [comment]
@hestia49 에러 메시지를 알 수 있을까요?

**Comment by hestia49** [comment]
Problem 2: 0 pts (COMPILE ERROR)
RETCODE: 2

STDOUT:
(echo D.v SfLib.v P01.v P02.v P03.v P04.v P05.v P06.v P07.v P08.v P09.v P10.v E01_01.v E01_02.v E02_01.v E03_01.v E03_02.v E04_01.v E05_01.v E06_01.v E07_01.v E08_01.v E09_01.v E10_01.v) > _CoqProject
coq_makefile -f _CoqProject -o Makefile.coq
make -f Makefile.coq "P02.vo"
make[1]: Entering directory `/tmp/tmp6wjf0a36/run'
"coqdep" -c -slash -I .  "P02.v" > "P02.v.d" || ( RV=$?; rm -f "P02.v.d"; exit ${RV} )
make[1]: Leaving directory`/tmp/tmp6wjf0a36/run'
make[1]: Entering directory `/tmp/tmp6wjf0a36/run'
"coqc"  -q  -I .    P02
optimize_1mult
     : aexp -> aexp
make[1]: Leaving directory`/tmp/tmp6wjf0a36/run'

STDERR:
Warning: install target will copy files at the first level of the coq contributions installation directory; option -R is recommended
make[1]: **\* [P02.vo] Bus error (core dumped)
make[1]: **\* [P02.vo] Deleting file `P02.glob'
make: **\* [P02.vo] Error 2

라고 뜹니다

**Comment by AlexSeongJu-sr** [comment]
아직도 제출이 안되네요.. ㅜㅜ

**Comment by jeehoonkang** [comment]
@hestia49 이메일로 보내주시면 감사하겠습니다.

@djflstkddk 일단 재부팅했습니다.  문제가 재차 발생하는데, 좀 더 자세히 원인을 살펴보겠습니다.

**Comment by hestia49** [comment]
pl2016@sf.snu.ac.kr 메일로 submission 전체 파일을 보냈습니다. P02.v입니다.

**Comment by jeehoonkang** [comment]
@hestia49 Please check the email address..

**Comment by jeehoonkang** [comment]
@hestia49 pl2016@sf.snu.ac.kr

**Comment by hestia49** [comment]
메일 다시 보냈습니다. 확인 부탁드립니다.

**Comment by jeehoonkang** [comment]
@hestia49 님의 제출물이 4GB이 넘는 RAM을 사용하는 것 같습니다.. 그래서 4GB가 달린 채점 서버가 계속 죽었던 것으로 보입니다.
- 혹시 적은 RAM을 사용하도록 제출을 수정해주실 수 있으신가요?
- Out of memory 상황을 검출할 수 있도록 서버를 수정하겠습니다.

**Comment by hestia49** [comment]
제 컴파일 환경도 4GB RAM인데 정상적으로 동작합니다. 혹시 다른 이유가 있는 것 아닐까요...

**Comment by jeehoonkang** [comment]
- 제 local에서는 memory를 5-6gb정도 먹었습니다.  아마 swap이 해결해준게 아닌가 싶습니다.
- 채점 서버의 용량을 일단 8gb로 올리려고 합니다.

**Comment by jeehoonkang** [comment]
일단 ram을 8gb로 올렸습니다.  다시 한 번 확인해보시겠습니까?

**Comment by hestia49** [comment]
통과했습니다 할렐루야 조교님 감사합니다

**Comment by AlexSeongJu-sr** [comment]
앗 과제 7제출시 저도 2번이 컴파일 에러가 납니다. 일단 메일로 보내겠습니다.
