### ISSUE TITLE
How to download a folder with assignment

### ISSUE THREAD

**Issue by k32l** [snu-sf-class/pl2016#7]
How to download an assignment folder to work with it?

**Comment by jeehoonkang** [comment]
- Learn git, or
- The github page has the "Download" link.

**Comment by k32l** [comment]
Sir, so we need to download page over again each time the new assignment comes out? I also know how to download each file seperately but it is time consuming if you want to download the whole folder.

**Comment by jeehoonkang** [comment]
Just call me Jeehoon. . .

I recommend you to download the whole folder each time, if you wanna download each time.  But I think downloading it via Git is much more recommended.

**Comment by jeehoonkang** [comment]
https://github.com/snu-sf-class/pl2016/issues/13
