### ISSUE TITLE
8번 숙제 make 가 계속 안 됩니다.

### ISSUE THREAD

**Issue by wjdtmdrms** [snu-sf-class/pl2016#71]
숙제 하려고 하는데 D.v 파일 쓰려면 make 를 해야 하잖아요~?
그런데 make 하면 응답 없음 상태에서 몇십분이 지나도 넘어가질 않습니다 ㅠㅠ

그냥 제 컴 성능 때문일까요? ㅠ
이전 숙제들은 D.v 때문에 make 하면 금방 됐는데 이번껀 왜 이러는지 ㅠㅠ

어떻게 해야 할 지 모르겠습니다 ㅠㅠ 다시 받아봐도 그래요..

모든 .v 파일의 .d 파일도 생성됐고 sfLib 도 컴파일 됩니다.
D.v 는 실행시키면 끝까진 되는데 compile 시키면 이거도 한참동안 응답없음으로 진행이 안 되구요..

P01.v 에서 make 시켜도 한참동안 응답없음에서 넘어가질 않아요 ㅠㅠ

**Comment by jeehoonkang** [comment]
Dear @wjdtmdrms ,
 May I ask what was the reason?

**Comment by wjdtmdrms** [comment]
8번 D.v 의 마지막 eval 을 주석처리 하니까 컴파일이 바로 됐어요 ㅠ
