### ISSUE TITLE
하드를 바꿨는데 make가 안됩니다 

### ISSUE THREAD

**Issue by AlexSeongJu-sr** [snu-sf-class/pl2016#72]
cygwin에서 which coqc을 하면 다음과 같이 뜹니다.
which: no coqc in (~~~~~~어쩌구저쩌구 /v1.0:[THE_DIRECTORY_CONTAINS_COQ])
제가 뭔가 PATH를 잘못넣은거같은데 뭘 잘못했는지 모르겠습니다
한번 봐주실 수 있으신지요..

감사합니다.

[BASH파일들.zip](https://github.com/snu-sf-class/pl2016/files/253586/BASH.zip)

**Comment by jeehoonkang** [comment]
`[THE_DIRECTORY_CONTAINS_COQ]` 대신에 진짜로 Coq을 설치한 directory를 넣어야 합니다.

**Comment by jeehoonkang** [comment]
"For Windows, the directory is highly likely `/cygdrive/c/Program\ Files\ \(x86\)/Coq/bin/`." from https://github.com/snu-sf-class/pl2016#coq

**Comment by AlexSeongJu-sr** [comment]
아맞다 ㅋㅋㅋㅋ 아 감사합니다

**Comment by AlexSeongJu-sr** [comment]
아 그런데 아직도 안됩니다. 
[bash파일들.zip](https://github.com/snu-sf-class/pl2016/files/253867/bash.zip)
which coqc를 치면 다음과 같이 뜹니다. 
which: no coqc in (/usr/~어쩌구저쩌구 /v1.0: [/cygdrive/c/Program Files (x86)/coq/bin/])

제가 coq/bin에 coqc가 들어있는것을 확인했는데 뭐가 잘못됐는지 모르겠습니다.
![kakaotalk_20160508_195256100](https://cloud.githubusercontent.com/assets/17724614/15097451/9342a770-1556-11e6-8215-d8bf2c73f3ac.png)

죄송한데 한번 봐주시면 감사드리겠습니다.

**Comment by AlexSeongJu-sr** [comment]
아 해결했습니다..
