### ISSUE TITLE
sf 교재에서 수업시간에 다룬 범위

### ISSUE THREAD

**Issue by swchoi06** [snu-sf-class/pl2016#76]
조교님. 혹시 sf 교재에서 수업시간에 다룬 부분들 정리해서 올려주실 수 있나요?

중간고사 이후부터 진도를 엄청 빠르게 나가시네요

수업 중간에 건너뛰는 부분들도 있던데 정리가 잘안되서 이슈 올려봅니다.

**Comment by jeehoonkang** [comment]
저도 교수님께서 어떤 부분을 다루시는지 잘 모르겠습니다.  @gilhur 교수님께 여쭤보는 것이 좋을 것 같습니다.

**Comment by jeehoonkang** [comment]
교수님께서 말씀하시길, https://www.cis.upenn.edu/~bcpierce/sf/current/deps.html 여기서 파란색 선만 따라가서 Smallstep까지 하셨다고 합니다.
