### ISSUE TITLE
coqc가 Program Files에 있는경우 bash profile 파일에서 path설정

### ISSUE THREAD

**Issue by AlexSeongJu-sr** [snu-sf-class/pl2016#83]
path 설정할때 

export PATH=$PATH:/cygdrive/c/Program\ Files\ /Coq/bin/

이런식으로 하면 될것 같은데 안됩니다. 
정확히 뭐라고 경로를 입력해야 할까요?
coqc의 directory는
 Program Files/coq/bin/ 에 있는게 맞습니다.

**Comment by jeehoonkang** [comment]
제 생각에는 경로 지정이 틀렸을 것 같습니다..
- `...Files \ /Coq...`에서 `\ /`의 의미는 무엇인가요?
- 터미널에서 `ls /cygdrive/c/P` 치신 후, Tab 버튼 눌러서 자동완성 시켜보세요.  자동완성되는 경로대로 치시면 됩니다.

**Comment by AlexSeongJu-sr** [comment]
아하 이제 됩니다. 감사합니다!
