### ISSUE TITLE
출석 관련하여 문의가 있습니다

### ISSUE THREAD

**Issue by Ailrun** [snu-sf-class/pl2016#84]
공지의 결석 6회가 F라는 부분을 보고 문의 드립니다.
강의에서 출석을 부르는 것을 듣지 못했는데,
제가 앞뒤로 타대수업이 있어 조금 늦거나 조금 빨리 나오기는 했지만 아예 듣지 못한 것은 이상하여 문의 드립니다.
출석체크가 있었나요? 있었다면 이메일로 관련 문의를 드릴 수 있을까요?

**Comment by jeehoonkang** [comment]
@gilhur 교수님께서 출석을 체크하셨습니다.  교수님께 여쭤보겠습니다.

**Comment by swchoi06** [comment]
저도 출석사항이 궁금한데 같이 보내주시거나, 공개해주실수있나요?

**Comment by jeehoonkang** [comment]
교수님께 메일 드렸는데, 아직 답이 없으셨습니다.  답이 오는대로 공지해드리겠습니다.
